maven_jar(
  name='org_apache_maven',
  artifact='org.apache.maven:maven-plugin-api:2.0',
)
maven_jar(
  name='log4j',
  artifact='log4j:log4j:1.2.17',
)
maven_jar(
  name='jraw',
  #artifact='net.dean.jraw:JRAW:0.7.0.3',
  artifact='net.dean.jraw:JRAW:0.6.1',
  repository='http://jcenter.bintray.com'
)
maven_jar(
  name='okhttp',
  artifact='com.squareup.okhttp:okhttp:2.2.0',
)
maven_jar(
  name='jackson_jaxrs',
  artifact='org.codehaus.jackson:jackson-jaxrs:1.9.13',
)
maven_jar(
  name='javax_javaee',
  artifact='javax:javaee-api:7.0'
  )
maven_jar(
  name='jackson_mapper_asl',
  artifact='org.codehaus.jackson:jackson-core-asl:1.9.13',
  #server='http://central.maven.org/maven2'
)
maven_jar(
  name='slf4j',
  artifact='org.slf4j:slf4j-api:1.7.7',
)
maven_jar(
  name='guava',
  artifact='com.google.guava:guava:18.0',
)
maven_jar(
  name='junit',
  artifact='junit:junit:4.12',
)
maven_jar(
  name='joda_time',
  artifact='joda-time:joda-time:2.6',
)
maven_jar(
  name='twitter4j',
  artifact='org.twitter4j:twitter4j-core:4.0.3',
)
maven_jar(
  name='json',
  artifact='org.json:json:20090211',
)
maven_jar(
  name='guice',
  artifact='com.google.inject:guice:3.0',
)
maven_jar(
  name='aopalliance',
  artifact='aopalliance:aopalliance:1.0',
  )
